name: Update Cloudfront and deploy code to S3 


on:

  push:

    branches:

    - master


jobs:

  deploy:

    runs-on: ubuntu-latest
        
    steps:
    # Checkout this repo

    - uses: actions/checkout@v2


    # Download a specific Terraform version you'd like to use

    - uses: hashicorp/setup-terraform@v1

      with:

        terraform_version: 1.0.8

        terraform_wrapper: false


    # Ensure you have AWS credentials set up. Your config will likely differ here

    - name: Configure AWS Credentials

      uses: aws-actions/configure-aws-credentials@v1

      with:

        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        role-skip-session-tagging: true

        role-duration-seconds: 1200

        aws-region: us-east-1


    # Apply the Terraform code

    - run: terraform init

    - run: terraform validate

    - run: terraform plan -out planfile

    - run: terraform apply planfile

    # Update bucket policy and invalidate cache.

    - run: aws s3api put-bucket-policy --bucket symbiotesorg-development-s3-origin --policy file://policy.json
    
    - run: aws cloudfront create-invalidation --distribution-id E3H86F78U0XHO6 --paths "/index.html" "/error.html"

